tugas 8/SIK/routes/web.php
<?php

use App\Http\Controllers\Home;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\EducationController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\TeacherEducationController;
use App\Http\Controllers\TeacherCourseController;
use App\Http\Controllers\StudentCourseController;

Route::redirect('/', 'auth/login');

Route::middleware(['auth', 'verified'])
    ->group(
        function () {
            Route::get('/home', Home::class)->name('home');
        }
    );

Route::resource('teacher', TeacherController::class);

Route::resource('teacher_education', TeacherEducationController::class);

Route::resource('teacher_course', TeacherCourseController::class);

Route::resource('student', StudentController::class);

Route::resource('student_course', StudentCourseController::class);

Route::resource('education', EducationController::class);

Route::resource('course', CourseController::class);

include __DIR__.'/auth.php';
include __DIR__.'/my.php';

tugas 8/SIK/app/Models/Education.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Education extends Model
{
    use HasFactory;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'education';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'strata', 'jurusan', 'sekolah', 'tahun_mulai', 'tahun_selesai',
    ];

    public function teachers(){
        return $this->belongsToMany('App\Models\Teacher');
    }
}

tugas 8/SIK/app/Http/Controllers/EducationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Education;
use App\Http\Requests\EducationStoreRequest;

class EducationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $education = Education::paginate(10);

        return view('education.index', compact('education'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('education.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(EducationStoreRequest $request)
    {
        Education::create($request->except('_token'));

        return redirect()->route('education.index')->withSuccess('Riwayat Pendidikan Berhasil Disimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Education $education)
    {
        return view('education.edit', compact('education'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(EducationStoreRequest $request, Education $education)
    {
        $education->update($request->except('_token'));

        return redirect()->route('education.index')->withSuccess('Riwayat Pendidikan Berhasil Diperbarui');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Education $education)
    {
        $education->delete();

        return redirect()->back()->withSuccess('Riwayat Pendidikan Berhasil Dihapus');
    }
}

tugas 8/SIK/resources/views/education/create.blade.php
<x-volt-app title="Pendidikan">

    {!! form()->post(route('education.store')) !!}
    {!! form()->text('strata')->label('Strata') !!}
    {!! form()->text('jurusan')->label('Jurusan') !!}
    {!! form()->text('sekolah')->label('Sekolah') !!}
    {!! form()->text('tahun_mulai')->label('Tahun Mulai') !!}
    {!! form()->text('tahun_selesai')->label('Tahun Selesai') !!}
    {!! form()->link('Batal', route('education.index')) !!}
    {!! form()->submit('Simpan') !!}
    {!! form()->close() !!}

</x-volt-app>

tugas 8/SIK/resources/views/education/edit.blade.php
<x-volt-app title="Pendidikan">

    {!! form()->bind($education)->put(route('education.update', $education->id)) !!}
    {!! form()->text('strata')->label('Strata') !!}
    {!! form()->text('jurusan')->label('Jurusan') !!}
    {!! form()->text('sekolah')->label('Sekolah') !!}
    {!! form()->text('tahun_masuk')->label('Tahun Masuk') !!}
    {!! form()->text('tahun_selesai')->label('Tahun Selesai') !!}
    {!! form()->link('Batal', route('education.index')) !!}
    {!! form()->submit('Perbarui') !!}
    {!! form()->close() !!}

</x-volt-app>

tugas 8/SIK/resources/views/education/index.blade.php
<x-volt-app title="Pendidikan">

@include('css.myCss')

    <a href="{{ route('education.create') }}">
        <button type="button" class="btn btn-light">+ Tambah Riwayat Pendidikan</button>
    </a>
    

    {!! Suitable::source($education)->columns([
        \Laravolt\Suitable\Columns\Numbering::make('No'),
        \Laravolt\Suitable\Columns\Text::make('strata', 'Strata'),
        \Laravolt\Suitable\Columns\Text::make('jurusan', 'Jurusan'),
        \Laravolt\Suitable\Columns\Text::make('sekolah', 'Sekolah'),
        \Laravolt\Suitable\Columns\Text::make('tahun_mulai', 'Tahun Mulai'),
        \Laravolt\Suitable\Columns\Text::make('tahun_selesai', 'Tahun Selesai'),
        \Laravolt\Suitable\Columns\RestfulButton::make('education', 'Action')->except("show")
        ])->render()
    !!}

    <a href="{{ route('home') }}">
        <button type="button" class="btn btn-light">< Kembali</button>
    </a>

</x-volt-app>